export const fundamentos = [
    {
        "id": 4,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "84 AL 91",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": "https://tramites.nayarit.gob.mx/reportes/index/241",
        "documento": null,
        "area_responsable": "Tesorería",
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": "1",
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": 2,
        "estados_globales": 1
    },
    {
        "id": 5,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "7",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": "https://tramites.nayarit.gob.mx/reportes/index/241",
        "documento": null,
        "area_responsable": "Tesorería",
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": "",
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": 2,
        "estados_globales": 1
    },
    {
        "id": 6,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "55 AL 66",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": "https://tramites.nayarit.gob.mx/reportes/index/241",
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": "",
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": 2,
        "estados_globales": 1
    },
    {
        "id": 7,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "4",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": "https://tramites.nayarit.gob.mx/reportes/index/241",
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": "",
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": 2,
        "estados_globales": 1
    },
    {
        "id": 8,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "65 AL 75",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 9,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "5",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 10,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "7 AL 9",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": null,
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 11,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "3",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 12,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "88",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 13,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "86",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 14,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "55 AL 59",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 15,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "10 AL 15",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": null,
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 16,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "13",
        "fraccion": null,
        "inciso": null,
        "parrafo": "Tercero",
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": null,
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 17,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "85",
        "fraccion": null,
        "inciso": null,
        "parrafo": "Segundo y Tercero",
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 18,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "72 AL 75",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 19,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "72 AL 75",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 20,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "66 Y 91",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 21,
        "denominacion": "Reglamento interior de la secretaría de administración y finanzas",
        "articulo": "36",
        "fraccion": "IV, V Y X",
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2020-12-10",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 5,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "REGLAMENTO INTERIOR DE LA SECRETARÍA DE ADMINISTRACIÓN Y FINANZAS",
            "fecha_de_publicacion": "2020-12-10",
            "fecha_de_vigor": "2022-01-01",
            "hipervinculo": "https://www.nayarit.gob.mx/transparenciafiscal/marcoregulatorio/ordenamientos/marcoregulatorio/reglamento_administracion.pdf",
            "tipo_de_ordenamiento": {
                "id": 21,
                "descripcion": "Reglamento",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 22,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "95",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": "A",
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 23,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "26",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 24,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "26.",
        "fraccion": null,
        "inciso": "I",
        "parrafo": null,
        "numero": null,
        "letra": "A, B, D, E",
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 25,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "11",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 26,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "12",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 27,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "13.",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 28,
        "denominacion": "Manual de procedimientos de la secretaría de administración y finanzas",
        "articulo": "Único",
        "fraccion": "I-Alta de vehículos B) Usados",
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-09-30",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 6,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "MANUAL DE PROCEDIMIENTOS DE LA SECRETARÍA DE ADMINISTRACIÓN Y FINANZAS",
            "fecha_de_publicacion": "2021-09-30",
            "fecha_de_vigor": "2022-01-01",
            "hipervinculo": null,
            "tipo_de_ordenamiento": {
                "id": 21,
                "descripcion": "Reglamento",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 29,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "26-",
        "fraccion": "IV",
        "inciso": "A",
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 30,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "-26",
        "fraccion": "IV.",
        "inciso": "B",
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 31,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "26_",
        "fraccion": "III",
        "inciso": "C",
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 32,
        "denominacion": "Manual de procedimientos de la secretaría de administración y finanzas",
        "articulo": "Único.",
        "fraccion": "Baja de vehículos",
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-09-30",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 6,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "MANUAL DE PROCEDIMIENTOS DE LA SECRETARÍA DE ADMINISTRACIÓN Y FINANZAS",
            "fecha_de_publicacion": "2021-09-30",
            "fecha_de_vigor": "2022-01-01",
            "hipervinculo": null,
            "tipo_de_ordenamiento": {
                "id": 21,
                "descripcion": "Reglamento",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 33,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "63",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-23",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 34,
        "denominacion": "Ley de hacienda del estado de nayarit",
        "articulo": "91",
        "fraccion": "I",
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 4,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE HACIENDA DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-02",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes/hacienda_del_estado_de_nayarit_ley_de.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 35,
        "denominacion": "Ley de ingresos del estado libre y soberano de nayarit",
        "articulo": "22",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2021-12-08",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 67,
        "denominacion": "Ley de transito del estado de nayarit",
        "articulo": "2",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2020-01-07",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 2,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE MOVILIDAD DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2020-01-07",
            "fecha_de_vigor": "2022-01-01",
            "hipervinculo": "https://www.contraloria.nayarit.gob.mx/assets/pdf/normateca/40.%20LEY%20DE%20MOVILIDAD%20DEL%20ESTADO%20DE%20NAYARIT.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 68,
        "denominacion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
        "articulo": "34",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2022-12-27",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 69,
        "denominacion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
        "articulo": "23",
        "fraccion": null,
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2022-12-27",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 1,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE INGRESOS DEL ESTADO LIBRE Y SOBERANO DE NAYARIT",
            "fecha_de_publicacion": "2022-12-27",
            "fecha_de_vigor": "2023-01-01",
            "hipervinculo": "https://congresonayarit.gob.mx/wp-content/uploads/QUE_HACEMOS/LEGISLACION_ESTATAL/leyes_ingresos_presupuesto/2023/ley_ingresos_2023_estado_nayarit.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    },
    {
        "id": 70,
        "denominacion": "LEY DE MOVILIDAD DEL ESTADO DE NAYARIT",
        "articulo": "432",
        "fraccion": "I.",
        "inciso": null,
        "parrafo": null,
        "numero": null,
        "letra": null,
        "hipervinculo": null,
        "documento": null,
        "area_responsable": null,
        "fecha_publicacion": "2020-01-07",
        "otro": null,
        "otro_fundamento_legal": null,
        "nombre_de_ordenamiento": {
            "id": 2,
            "fecha_de_vigencia": null,
            "autoridad_emite": null,
            "autoridad_aplica": null,
            "fecha_actualizada": null,
            "indice_regulacion": null,
            "objeto_regulacion": null,
            "materia": null,
            "sector": null,
            "sujetos_regulados": null,
            "nombre_tramites_relacionados": null,
            "identificacion_fundamentos": null,
            "otras_regulaciones_vinculadas": null,
            "descripcion": "LEY DE MOVILIDAD DEL ESTADO DE NAYARIT",
            "fecha_de_publicacion": "2020-01-07",
            "fecha_de_vigor": "2022-01-01",
            "hipervinculo": "https://www.contraloria.nayarit.gob.mx/assets/pdf/normateca/40.%20LEY%20DE%20MOVILIDAD%20DEL%20ESTADO%20DE%20NAYARIT.pdf",
            "tipo_de_ordenamiento": {
                "id": 11,
                "descripcion": "Ley",
                "estados_globales": 1
            },
            "ambito_de_ordenamiento": {
                "id": 1,
                "descripcion": "Estatal",
                "estados_globales": 1
            },
            "estados_globales": 1
        },
        "normatividad": null,
        "estados_globales": 1
    }
]