export const TiposConceptosSchema = {
    name: 'TiposConcepto',
    primaryKey: 'id',
    properties: {
      id: 'int',
      clave: 'string',
      descripcion: 'string',
      es_concepto_capturable: 'bool',
      es_visible: 'bool',
      es_concepto_repetible: 'bool',
      maximo_de_concepto_repetido: 'int',
      es_importe_capturable: 'bool',
      importe_de_moneda_fija_inicial: 'double',
      importe_de_moneda_minima: 'double',
      importe_de_moneda_maxima: 'double',
      fundamento_legal: 'int?', 
      descripcion_corta: 'mixed?',
      monedas: 'int',
      capturable_de_fecha_inicial: 'bool',
      capturable_de_fecha_final: 'bool',
      capturable_de_nota_de_concepto: 'bool',
      periodo_fiscal: 'int',
      clase_de_concepto_de_infraccion: 'int',
      tipo_de_cargo: 'int',
      grua: 'mixed?', 
      examen_medico: 'mixed?', 
      yarda: 'mixed?', 
    },
  };